---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG FOR R2
  hosts: R2
  gather_facts: false
  
  vars:
    cli:
      username: cisco
      password: cisco123!
      timeout: 100
      auth_pass: cisco

  tasks:
   - name: APPLYING OSPF TO R2
     ios_config:
       provider: "{{ cli }}"
       authorize: yes
       lines: 
         - router-id 1.1.1.2
         - passive-interface f0/0
         - passive-interface f0/1
         - network 10.0.0.0 0.0.0.3 area 0
         - network 10.0.0.4 0.0.0.3 area 0
         - network 172.16.1.0 0.0.0.3 area 0
         - network 150.9.23.80 0.0.0.7 area 0
       parents: router ospf 1

   - name: APPLYING ACCESS LIST FOR MANAGER AREA RESTRICTIONS
     ios_config:
       provider: "{{ cli }}"
       authorize: yes
       lines: 
         - deny 150.9.23.0 0.0.0.63
         - deny 150.9.23.64 0.0.0.15
         - permit any
       parents: ip access-list standard MANAGER_AREA_RESTRICTIONS
   
   - name: APPLYING ACCESS GROUP TO THE INTERFACE F0/1
     ios_config:
       provider: "{{ cli }}"
       authorize: yes
       lines: 
         - int f0/1
         - ip access-group MANAGER_AREA_RESTRICTIONS out

   - name: DISPLAYING THE RUNNING-CONFIG
     ios_command:
       provider: "{{ cli }}"
       authorize: yes
       commands:
         - show run
         - wr
     register: config

   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "backups/show_run_R2.txt"

- name: AUTOMATIC BACKUP OF RUNNING-CONFIG FOR R1
  hosts: R1
  gather_facts: false
  
  vars:
    cli:
      username: cisco
      password: cisco123!
      timeout: 100
      auth_pass: cisco

  tasks:
   - name: APPLYING OSPF TO R1
     ios_config:
       provider: "{{ cli }}"
       authorize: yes
       lines: 
         - router-id 1.1.1.1
         - network 10.0.0.0 0.0.0.3 area 0
         - network 10.0.0.8 0.0.0.3 area 0
         - default-information originate
       parents: router ospf 1
   
   - name: APPLYING ACCESS-LIST TO R1 FOR THE PAT
     ios_config:
       provider: "{{ cli }}"
       authorize: yes
       lines: 
         - access-list 1 permit 150.9.23.80 0.0.0.7
         - access-list 2 permit 172.16.1.0 0.0.0.3

   - name: APPLYING PAT TO R1
     ios_config:
       provider: "{{ cli }}"
       authorize: yes
       lines: 
         - ip nat pool MANAGER_AREA_POOL 213.210.20.1 213.210.20.2 netmask 255.255.255.252
         - ip nat pool ADMIN_AREA_POOL 213.210.30.1 213.210.30.2 netmask 255.255.255.252
         - ip nat inside source list 1 pool MANAGER_AREA_POOL overload
         - ip nat inside source list 2 pool ADMIN_AREA_POOL overload
 
   - name: DISPLAYING THE RUNNING-CONFIG
     ios_command:
       provider: "{{ cli }}"
       authorize: yes
       commands:
         - show run
         - wr 
     register: config

   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "backups/show_run_R1.txt"

- name: AUTOMATIC BACKUP OF RUNNING-CONFIG FOR R3
  hosts: R3
  gather_facts: false
  
  vars:
    cli:
      username: cisco
      password: cisco123!
      timeout: 100
      auth_pass: cisco

  tasks:
   - name: APPLYING OSPF TO R3
     ios_config:
       provider: "{{ cli }}"
       authorize: yes
       lines: 
         - router-id 1.1.1.3
         - passive-interface f0/0
         - passive-interface f0/1
         - network 10.0.0.8 0.0.0.3 area 0
         - network 10.0.0.4 0.0.0.3 area 0
         - network 150.9.23.0 0.0.0.63 area 0
         - network 150.9.23.64 0.0.0.15 area 0
       parents: router ospf 1

   - name: DISPLAYING THE RUNNING-CONFIG
     ios_command:
       provider: "{{ cli }}"
       authorize: yes
       commands:
         - show run
         - wr
     register: config

   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "backups/show_run_R3.txt"